[2022-07-29T12:08:21] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'IHDR' 16 13
[2022-07-29T12:08:21] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'sRGB' 41 1
[2022-07-29T12:08:21] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'IDAT' 54 8192
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing BlpImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing BmpImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing BufrStubImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing CurImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing DcxImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing DdsImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing EpsImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing FitsImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing FitsStubImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing FliImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing FpxImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:404] Image: failed to import FpxImagePlugin: No module named 'olefile'
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing FtexImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing GbrImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing GifImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing GribStubImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing Hdf5StubImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing IcnsImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing IcoImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing ImImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing ImtImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing IptcImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing JpegImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing Jpeg2KImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing McIdasImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing MicImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:404] Image: failed to import MicImagePlugin: No module named 'olefile'
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing MpegImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing MpoImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing MspImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PalmImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PcdImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PcxImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PdfImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PixarImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PngImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PpmImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PsdImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing SgiImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing SpiderImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing SunImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing TgaImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing TiffImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing WebPImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing WmfImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing XbmImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing XpmImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing XVThumbImagePlugin
[2022-07-29T12:10:31] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\apps\models.py changed, reloading.
[2022-07-29T12:11:45] INFO [root.logout:188] admin_ logged out
[2022-07-29T12:11:48] INFO [root.logout:188] _ logged out
[2022-07-29T12:11:50] INFO [root.showapps:43] admin_seen the whole applist
[2022-07-29T12:11:51] ERROR [django.request.log_response:224] Internal Server Error: /apps/all/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'ImageFieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\saketh\Downloads\billapp\apps\views.py", line 44, in showapps
    return render(request,'showapps.html',{'showapp':appli,'leni':leni,'msg':mssg})
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\fields\files.py", line 63, in url
    self._require_file()
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\fields\files.py", line 40, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'appimg' attribute has no file associated with it.
[2022-07-29T12:12:29] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'IHDR' 16 13
[2022-07-29T12:12:29] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'sRGB' 41 1
[2022-07-29T12:12:29] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'IDAT' 54 8192
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing BlpImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing BmpImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing BufrStubImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing CurImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing DcxImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing DdsImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing EpsImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing FitsImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing FitsStubImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing FliImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing FpxImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:404] Image: failed to import FpxImagePlugin: No module named 'olefile'
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing FtexImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing GbrImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing GifImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing GribStubImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing Hdf5StubImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing IcnsImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing IcoImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing ImImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing ImtImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing IptcImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing JpegImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing Jpeg2KImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing McIdasImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing MicImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:404] Image: failed to import MicImagePlugin: No module named 'olefile'
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing MpegImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing MpoImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing MspImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PalmImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PcdImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PcxImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PdfImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PixarImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PngImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PpmImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PsdImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing SgiImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing SpiderImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing SunImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing TgaImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing TiffImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing WebPImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing WmfImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing XbmImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing XpmImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing XVThumbImagePlugin
[2022-07-29T12:12:34] INFO [root.showapps:43] admin_seen the whole applist
[2022-07-29T12:12:37] INFO [root.showapps:43] admin_seen the whole applist
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-xd.svg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-atlassian.svg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-spotify.svg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-slack.svg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-invision.svg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-jira.svg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/chartjs.min.js
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T12:12:44] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/estimate.html
[2022-07-29T12:12:45] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T12:14:36] WARNING [django.request.log_response:224] Not Found: /admin/instagram
[2022-07-29T12:15:45] WARNING [django.request.log_response:224] Not Found: /favicon.ico
[2022-07-29T12:16:09] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:19:14] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:29:20] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\views.py changed, reloading.
[2022-07-29T12:29:27] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:30:18] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:32:42] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:33:41] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:35:42] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:36:10] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:36:29] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:37:51] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:38:14] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:38:48] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:38:54] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:38:55] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:40:20] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:40:42] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:41:08] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:41:25] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\models.py changed, reloading.
[2022-07-29T12:42:02] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:42:12] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:43:56] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:44:24] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\models.py changed, reloading.
[2022-07-29T12:45:04] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\models.py changed, reloading.
[2022-07-29T12:45:27] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\models.py changed, reloading.
[2022-07-29T12:53:59] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:55:44] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:55:52] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:59:55] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\models.py changed, reloading.
[2022-07-29T13:01:41] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:02:12] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:03:21] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:03:36] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:04:05] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:04:22] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:05:19] ERROR [django.request.log_response:224] Internal Server Error: /update-profile-save/ruchitha/instagram
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 309, in check_response
    raise ValueError(
ValueError: The view accounts.views.update_profile_save didn't return an HttpResponse object. It returned None instead.
[2022-07-29T13:08:49] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\forms.py changed, reloading.
[2022-07-29T13:08:59] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\forms.py changed, reloading.
[2022-07-29T13:09:01] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\forms.py changed, reloading.
[2022-07-29T13:09:03] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\forms.py changed, reloading.
[2022-07-29T13:09:07] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\forms.py changed, reloading.
[2022-07-29T13:09:30] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:09:40] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:09:52] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:09:54] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:09:55] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:09:55] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:10:30] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:10:31] ERROR [django.request.log_response:224] Internal Server Error: /apps/create.html/add-customer-form/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\dashboard\views.py", line 206, in add_customer_form
    app = applists.objects.get(slug=slug)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
apps.models.applists.DoesNotExist: applists matching query does not exist.
[2022-07-29T13:11:15] ERROR [django.request.log_response:224] Internal Server Error: /apps/create.html/add-customer-form/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\dashboard\views.py", line 206, in add_customer_form
    app = applists.objects.get(slug=slug)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
apps.models.applists.DoesNotExist: applists matching query does not exist.
[2022-07-29T13:11:20] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:11:28] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:11:28] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:16:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/add-customer-form/create.html
[2022-07-29T14:16:42] WARNING [django.request.log_response:224] Not Found: /favicon.ico
[2022-07-29T14:18:03] WARNING [django.request.log_response:224] Not Found: /apps/instagram/add-customer-form/existing-user.html
[2022-07-29T14:18:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/add-customer-form/existing-user.html
[2022-07-29T14:19:11] WARNING [django.request.log_response:224] Not Found: /apps/instagram/add-customer-form/dashboard.html
[2022-07-29T14:19:17] WARNING [django.request.log_response:224] Not Found: /apps/instagram/add-customer-form/create.html
[2022-07-29T14:27:01] WARNING [django.request.log_response:224] Not Found: /apps/instagram/add-existing-user/styles.css
[2022-07-29T14:27:16] WARNING [django.request.log_response:224] Not Found: /apps/instagram/add-existing-user/styles.css
[2022-07-29T14:29:10] WARNING [django.request.log_response:224] Not Found: /apps/instagram/add-existing-user/styles.css
[2022-07-29T14:29:16] WARNING [django.request.log_response:224] Not Found: /apps/instagram/add-existing-user/styles.css
[2022-07-29T14:29:17] WARNING [django.request.log_response:224] Not Found: /favicon.ico
[2022-07-29T14:30:33] WARNING [django.request.log_response:224] Not Found: /favicon.ico
[2022-07-29T14:33:42] WARNING [django.request.log_response:224] Not Found: /apps/instagram/add-existing-user/customerlist.html
[2022-07-29T14:33:50] WARNING [django.request.log_response:224] Not Found: /apps/instagram/add-customer-form/customerlist.html
[2022-07-29T14:33:54] WARNING [django.request.log_response:224] Not Found: /apps/instagram/add-customer-form/dashboard.html
[2022-07-29T14:33:56] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T14:33:59] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T14:34:01] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T14:34:02] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T14:34:03] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:34:03] INFO [root.showapps:43] admin_seen the whole applist
[2022-07-29T14:34:18] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:34:37] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:34:38] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-xd.svg
[2022-07-29T14:34:38] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T14:34:38] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:34:38] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T14:34:38] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:34:38] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T14:34:38] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-atlassian.svg
[2022-07-29T14:34:38] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-slack.svg
[2022-07-29T14:34:38] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-spotify.svg
[2022-07-29T14:34:38] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-jira.svg
[2022-07-29T14:34:38] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-invision.svg
[2022-07-29T14:34:38] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/chartjs.min.js
[2022-07-29T14:34:38] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T14:34:38] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T14:35:36] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\views.py changed, reloading.
[2022-07-29T14:36:08] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-xd.svg
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-atlassian.svg
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-jira.svg
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-slack.svg
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-spotify.svg
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-invision.svg
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/chartjs.min.js
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T14:36:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:36:33] WARNING [django.request.log_response:224] Not Found: /apps/instagram/add-customer-form/customerlist.html
[2022-07-29T14:38:01] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\views.py changed, reloading.
[2022-07-29T14:38:37] INFO [root.showapps:43] admin_seen the whole applist
[2022-07-29T14:40:17] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/estimate.html
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-xd.svg
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-atlassian.svg
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-slack.svg
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-spotify.svg
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-jira.svg
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-invision.svg
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/chartjs.min.js
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:40:20] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:40:21] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:40:21] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T14:40:21] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-xd.svg
[2022-07-29T14:40:21] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:40:21] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:40:21] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:40:21] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T14:40:21] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T14:40:22] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-atlassian.svg
[2022-07-29T14:40:22] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-slack.svg
[2022-07-29T14:40:22] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-spotify.svg
[2022-07-29T14:40:22] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-jira.svg
[2022-07-29T14:40:22] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-invision.svg
[2022-07-29T14:40:22] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/chartjs.min.js
[2022-07-29T14:40:22] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T14:40:22] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:40:22] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:40:22] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T14:44:28] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\dashboard\urls.py changed, reloading.
[2022-07-29T14:44:36] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\dashboard\urls.py changed, reloading.
[2022-07-29T14:44:45] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\dashboard\urls.py changed, reloading.
[2022-07-29T14:45:09] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\dashboard\views.py changed, reloading.
[2022-07-29T14:45:16] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\dashboard\views.py changed, reloading.
[2022-07-29T14:51:08] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-xd.svg
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-atlassian.svg
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-jira.svg
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-slack.svg
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-invision.svg
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-spotify.svg
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/chartjs.min.js
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T14:51:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:51:11] WARNING [django.request.log_response:224] Not Found: /apps/instagram/estimates/header.html
[2022-07-29T14:52:30] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-xd.svg
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-jira.svg
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-spotify.svg
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/chartjs.min.js
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-slack.svg
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-invision.svg
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-atlassian.svg
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T14:52:31] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:52:43] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:52:43] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T14:52:43] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-xd.svg
[2022-07-29T14:52:43] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:52:43] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:52:43] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T14:52:44] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T14:52:44] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-atlassian.svg
[2022-07-29T14:52:44] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-slack.svg
[2022-07-29T14:52:44] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-spotify.svg
[2022-07-29T14:52:44] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-jira.svg
[2022-07-29T14:52:44] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-invision.svg
[2022-07-29T14:52:44] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/chartjs.min.js
[2022-07-29T14:52:44] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T14:52:45] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:52:45] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T14:52:45] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:52:45] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:52:45] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T14:52:45] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-xd.svg
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-slack.svg
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-atlassian.svg
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-spotify.svg
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-jira.svg
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-invision.svg
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/chartjs.min.js
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:53:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T14:59:32] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:59:32] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T14:59:32] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-xd.svg
[2022-07-29T14:59:33] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T14:59:33] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:59:33] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T14:59:33] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T14:59:33] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-atlassian.svg
[2022-07-29T14:59:33] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-slack.svg
[2022-07-29T14:59:33] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-spotify.svg
[2022-07-29T14:59:33] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-jira.svg
[2022-07-29T14:59:33] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-invision.svg
[2022-07-29T14:59:33] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/chartjs.min.js
[2022-07-29T14:59:33] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T14:59:34] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T14:59:34] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T14:59:35] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T14:59:35] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T14:59:35] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T14:59:35] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-xd.svg
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-atlassian.svg
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-spotify.svg
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-jira.svg
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-invision.svg
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-slack.svg
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/chartjs.min.js
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T15:00:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T15:02:05] WARNING [django.request.log_response:224] Not Found: /apps/instagram/estimates/create.html
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-xd.svg
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-slack.svg
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-atlassian.svg
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-spotify.svg
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-jira.svg
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-invision.svg
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/chartjs.min.js
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T15:02:14] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T15:04:03] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T15:04:03] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T15:04:03] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-xd.svg
[2022-07-29T15:04:03] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T15:04:03] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T15:04:03] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T15:04:03] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-atlassian.svg
[2022-07-29T15:04:03] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T15:04:03] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T15:04:03] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-slack.svg
[2022-07-29T15:04:03] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-spotify.svg
[2022-07-29T15:04:03] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-jira.svg
[2022-07-29T15:04:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-invision.svg
[2022-07-29T15:04:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/chartjs.min.js
[2022-07-29T15:04:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T15:04:04] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:32:23] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/image/profile1.jpg
[2022-07-29T15:32:23] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T15:32:23] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:36:22] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T15:36:23] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:36:32] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T15:36:32] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:38:41] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T15:38:41] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:38:52] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T15:38:52] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:39:36] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:40:19] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:40:24] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:40:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:40:45] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:41:03] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:41:40] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:44:59] ERROR [django.request.log_response:224] Internal Server Error: /apps/instagram/add-customer-form/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\dashboard\views.py", line 211, in add_customer_form
    return render(request, 'add_customer_app.html', {'app': app})
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' with arguments '('',)' not found. 2 pattern(s) tried: ['dash/dashboard/\\Z', 'apps/(?P<slug>[^/]+)/dashboard/\\Z']
[2022-07-29T15:50:36] ERROR [django.request.log_response:224] Internal Server Error: /apps/instagram/add-customer-form/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\dashboard\views.py", line 211, in add_customer_form
    return render(request, 'add_customer_app.html', {'app': app})
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' with arguments '('',)' not found. 2 pattern(s) tried: ['dash/dashboard/\\Z', 'apps/(?P<slug>[^/]+)/dashboard/\\Z']
[2022-07-29T15:50:54] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T15:50:55] ERROR [django.request.log_response:224] Internal Server Error: /apps/instagram/add-customer-form/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\dashboard\views.py", line 211, in add_customer_form
    return render(request, 'add_customer_app.html', {'app': app})
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' with arguments '('',)' not found. 2 pattern(s) tried: ['dash/dashboard/\\Z', 'apps/(?P<slug>[^/]+)/dashboard/\\Z']
[2022-07-29T15:50:58] ERROR [django.request.log_response:224] Internal Server Error: /apps/instagram/add-customer-form/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\dashboard\views.py", line 211, in add_customer_form
    return render(request, 'add_customer_app.html', {'app': app})
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' with arguments '('',)' not found. 2 pattern(s) tried: ['dash/dashboard/\\Z', 'apps/(?P<slug>[^/]+)/dashboard/\\Z']
[2022-07-29T15:51:38] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\dashboard\views.py changed, reloading.
[2022-07-29T15:56:06] ERROR [django.request.log_response:224] Internal Server Error: /apps/instagram/add-existing-user/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\dashboard\views.py", line 216, in add_existing_user
    return render(request, 'add_existing_user.html', {'profiles': profiles, 'app': app})
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' with arguments '('',)' not found. 2 pattern(s) tried: ['dash/dashboard/\\Z', 'apps/(?P<slug>[^/]+)/dashboard/\\Z']
[2022-07-29T15:56:32] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\dashboard\views.py changed, reloading.
[2022-07-29T15:58:11] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T16:02:25] WARNING [django.request.log_response:224] Not Found: /admin/instagram
[2022-07-29T16:02:28] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T16:02:33] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T16:02:36] WARNING [django.request.log_response:224] Not Found: /sdf/js/create.js
[2022-07-29T16:02:40] WARNING [django.request.log_response:224] Not Found: /sdfg/js/create.js
[2022-07-29T16:03:34] WARNING [django.request.log_response:224] Not Found: /apps/instagram/customerlist/bulk.html
[2022-07-29T16:04:48] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\dashboard\views.py changed, reloading.
[2022-07-29T16:04:56] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\dashboard\views.py changed, reloading.
[2022-07-29T16:05:00] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\dashboard\views.py changed, reloading.
[2022-07-29T16:05:05] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\dashboard\views.py changed, reloading.
[2022-07-29T16:05:27] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\dashboard\urls.py changed, reloading.
[2022-07-29T16:06:01] ERROR [django.request.log_response:224] Internal Server Error: /dash/bulkupload/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
TypeError: bulkup() missing 1 required positional argument: 'slug'
[2022-07-29T16:08:17] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T16:08:28] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T16:08:37] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T16:08:42] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T16:08:45] WARNING [django.request.log_response:224] Not Found: /apps/instagram/customerlist/bulk.html
[2022-07-29T16:11:53] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T16:12:40] WARNING [django.request.log_response:224] Not Found: /admin/instagram
[2022-07-29T16:12:46] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T16:13:09] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T16:13:11] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T16:13:12] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T16:13:12] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T16:13:12] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T16:13:16] WARNING [django.request.log_response:224] Not Found: /apps/instagram/customerlist/bulk.html
[2022-07-29T16:13:25] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T16:19:44] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T16:29:46] ERROR [django.request.log_response:224] Internal Server Error: /groups/panel/instagram
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\groups\views.py", line 21, in groups_panel
    return render(request, 'groups-panel/panel.html', payload)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 657, in __init__
    filter_func = parser.find_filter(filter_name)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 569, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'crispy'
[2022-07-29T16:38:01] ERROR [django.request.log_response:224] Internal Server Error: /groups/panel/instagram
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\groups\views.py", line 21, in groups_panel
    return render(request, 'groups-panel/panel.html', payload)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 657, in __init__
    filter_func = parser.find_filter(filter_name)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 569, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'crispy'
[2022-07-29T16:40:20] ERROR [django.request.log_response:224] Internal Server Error: /groups/panel/instagram
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\groups\views.py", line 21, in groups_panel
    return render(request, 'groups-panel/panel.html', payload)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 817, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 383: 'endif', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
[2022-07-29T16:55:15] ERROR [django.request.log_response:224] Internal Server Error: /groups/group/Hi6T8Yo3Tl
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\groups\views.py", line 62, in show_group
    return render(request, 'groups-panel/group.html', payload)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' with arguments '('',)' not found. 2 pattern(s) tried: ['dash/dashboard/\\Z', 'apps/(?P<slug>[^/]+)/dashboard/\\Z']
[2022-07-29T16:55:41] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\groups\views.py changed, reloading.
[2022-07-29T16:55:53] ERROR [django.request.log_response:224] Internal Server Error: /groups/group/Hi6T8Yo3Tl
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\groups\views.py", line 62, in show_group
    return render(request, 'groups-panel/group.html', payload,slug=slug)
TypeError: render() got an unexpected keyword argument 'slug'
[2022-07-29T16:56:15] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\groups\views.py changed, reloading.
[2022-07-29T16:56:20] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\groups\views.py changed, reloading.
[2022-07-29T16:56:24] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\groups\views.py changed, reloading.
[2022-07-29T16:56:32] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\groups\views.py changed, reloading.
[2022-07-29T16:56:35] ERROR [django.request.log_response:224] Internal Server Error: /groups/group/Hi6T8Yo3Tl
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\groups\views.py", line 62, in show_group
    return render(request, 'groups-panel/group.html', payload)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' with arguments '('',)' not found. 2 pattern(s) tried: ['dash/dashboard/\\Z', 'apps/(?P<slug>[^/]+)/dashboard/\\Z']
[2022-07-29T16:58:46] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T17:04:50] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T17:04:59] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T17:22:45] ERROR [django.request.log_response:224] Internal Server Error: /apps/instagram/settings
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\apps\views.py", line 76, in update_app
    return render(request, 'app_settings.html', payload)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' with arguments '('',)' not found. 2 pattern(s) tried: ['dash/dashboard/\\Z', 'apps/(?P<slug>[^/]+)/dashboard/\\Z']
[2022-07-29T17:26:35] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\groups\views.py changed, reloading.
[2022-07-29T17:29:04] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\groups\views.py changed, reloading.
[2022-07-29T17:29:28] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\groups\views.py changed, reloading.
[2022-07-29T17:29:32] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\groups\views.py changed, reloading.
[2022-07-29T17:29:35] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\groups\views.py changed, reloading.
[2022-07-29T17:29:39] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\groups\views.py changed, reloading.
[2022-07-29T17:29:43] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\groups\views.py changed, reloading.
[2022-07-29T17:29:46] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\groups\views.py changed, reloading.
[2022-07-29T17:30:01] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\groups\views.py changed, reloading.
